### PR TITLE
Thermaplugg updates

### PR DESCRIPTION
**Pull request by emmericp**

### CODE REVIEW

**Comment by MysticalOS** [comment]
Should also add a minsync revision, because otherwise an out of date mod can call an early wipe (and that's synced) which will result in the mod ending combat anyways. also, while at it, do you leave combat when bosses rotate too? if so, should also add a 25 second wipe timer too.

**Comment by emmericp** [comment]
> minsync revision,

good idea, done

>  do you leave combat when bosses rotate too?

no

**Comment by MysticalOS** [comment]
Oh one last thing, put todays date in hotfix revision too. for context of what that revision is, it's diff from min sync cause sometimes you can fix a critical bug that doesn't need a new minsync, but what it does is notify you that a newer version of that module is available that fixes bugs. i believe that notification only shows on a wipe though, i'd have to double check. I contextualized it as "if you're wiping to this boss, you should probably have newest module for it"

**Comment by emmericp** [comment]
done

**Review by MysticalOS — APPROVED** [review]

**Pull request merged**
